app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls'))
]

app/users/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
  path('login', views.login_view, name='login'),
  path('logout', views.logout_view, name='logout'),
  path('signup', views.signup_view, name='signup')
]

app/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
  student_id = models.CharField(max_length=10)

app/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .models import User

# Create your views here.

def login_view(request):
  if request.method == 'POST':
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)

    if user is not None:
      print('인증 성공')
      login(request, user)
    else:
      print('인증 실패')

  return render(request, 'users/login.html')

def logout_view(request):
  logout(request)
  return redirect('user:login')

def signup_view(request):
  if request.method == 'POST':
    print(request.POST)
    firstname = request.POST['firstname']
    lastname = request.POST['lastname']
    password = request.POST['password']
    email = request.POST['email']
    student_id = request.POST['student_id']

    user = User.objects.create_user(firstname + lastname, email, password)
    user.student_id = student_id
    user.save()

    return redirect('user:login')

  return render(request, 'users/signup.html')

app/users/templates/users/login.html
<html>
  <head>
    <title>로그인 페이지</title>
  </head>
  <body>
    {% if user.is_authenticated %}
    로그인 한 상태입니다.<br>
    {{ user.username }}님 환영합니다!

    <a href="{% url 'user:logout' %}">로그아웃</a>

    {% else %}
    <h1>로그인 페이지</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <input type="text" name="username">
      <input type="password" name="password">
      <input type="submit" value="로그인">
    </form>

    <a href="{% url 'user:signup' %}">회원가입</a>

    {% endif %}
  </body>
</html>

app/users/templates/users/signup.html
<html>
  <head>
    <title>회원가입</title>
    <style>
      input {
        display: block;
        margin-bottom: 20px;
      }
    </style>
  </head>
  <body>
    <h1>회원가입</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <label>성</label>
      <input type="text" name="firstname">

      <label>이름</label>
      <input type="text" name="lastname">

      <label>비밀번호</label>
      <input type="password" name="password">

      <label>이메일</label>
      <input type="text" name="email">

      <label>학번</label>
      <input type="text" name="student_id">

      <input type="submit" value="가입하기">
    </form>
  </body>
</html>